//Orders
export const REQUEST_ORDERS = 'ORDERS/REQUEST_ORDERS';
export const FETCH_ORDERS = 'ORDERS/FETCH_ORDERS';
export const SHOW_ORDERS_LOADER = 'ORDERS/SHOW_ORDERS_LOADER';
export const HIDE_ORDERS_LOADER = 'ORDERS/HIDE_ORDERS_LOADER';
export const SET_STATUS = 'ORDERS/SET_STATUS';
export const SET_PAGE = 'ORDERS/SET_PAGE';
export const SET_SORT = 'ORDERS/SET_SORT';
export const SELL_ORDERS = 'ORDERS/SELL_ORDERS';
export const ORDERS_SOLD = 'ORDERS/ORDERS_SOLD';

//App
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';
